type: sqlite
filename: ./foo.db
init:
  - "CREATE TABLE IF NOT EXISTS DAT_MOCK(ID INTEGER PRIMARY KEY AUTOINCREMENT,
    VALUE INTEGER NOT NULL);"
  - "CREATE TABLE IF NOT EXISTS DATA(ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT NOT NULL,
    VALUETYPE TEXT NOT NULL,
    RAWVALUE TEXT NOT NULL,
    CONVERSIONVALUE TEXT NOT NULL,
    SAMPLETIME DATETIME NOT NULL,
    SAMPLESTATUS INT);"
