type: QA
target: modbus
cron: "*/10 * * * * ?"
retry: 3
packet:
-
  transactionID: 0
  slaveID: 1
  address: 30001
  len: 2
  isWrite: false
  valueType: int
handler:
- type: report
  target: upsidemock