type: QA
target: modbus
cron: "*/10 * * * * ?"
retry: 3
packet:
-
  name: test
  transactionID: 0
  slaveID: 1
  address: 30001
  len: 1
  isWrite: false
  valueType: int
  # 读取超时时间，单位为ms
  timeout: 2000
handler:
- type: report
  target: upsidemock