type: QA
target: modbus_rtu_tcp
cron: "*/20 * * * * ?"
retry: 3
packet:
-
  name: AI03
  transactionID: 0
  slaveID: 1
  address: 40001
  len: 1
  isWrite: false
  valueType: int
  # 读取超时时间，单位为ms
  timeout: 2000
handler:
- type: sql
  sql: "INSERT INTO DATA(NAME, VALUETYPE, RAWVALUE, CONVERSIONVALUE, SAMPLETIME, SAMPLESTATUS)
  VALUES ('{{.Name}}', '{{.ValueType}}', '{{.RawValue}}', '{{.ConversionValue}}', datetime('now','localtime'), {{.SampleStatus}})"
  target: sqlite
- type: report
  target: rootcloud